root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && go build -o ./tmp/main ./cmd/"
  bin = "./tmp/main"
  delay = 500
  exclude_dir = ["static", "tmp", "bin", "node_modules"]
  exclude_regex = ["_templ\\.go$"]
  include_ext = ["go", "templ", "css"]
  kill_delay = "1s"

[screen]
  clear_on_rebuild = true

[misc]
  clean_on_exit = true
